# 상단에 있는 이 설정들이 핵심입니다
title: "RealityLab CVPR 2026 Challenge"
description: "RealityLab Challenge Website"

# 주소 설정 (이 두 줄이 디자인을 결정합니다)
url: "https://ri-mmu.github.io"
baseurl: "/cvpr-challenge-2026"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
css: ./assets/hotweb.css

# Build settings
markdown: kramdown
# gems:
exclude:
  - Gemfile
  - Gemfile.lock

timezone: America/New_York
google_analytics: UA-99357652-1

