title: "H-PRISM: Humanoid Precise Relational Interactions on Shelves and Manipulation"
description: "H-PRISM Challenge at CVPR 2026"

url: "https://ri-mmu.github.io"
baseurl: "/cvpr-challenge-2026"

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - LICENSE
